[package]
name = "pk2"
version = "0.1.0"
authors = ["mahmoudFarouk <mahmoud.farouk987@gmail.com>"]
edition = "2024"
description = "Read and modify Silkroad Online PK2 archives"
repository = "https://github.com/mahmoudfarouq/pk2"
readme = "README.md"
keywords = ["pk2", "silkroad", "archive"]
categories = ["filesystem", "parser-implementations"]

[dependencies]
